---
version: "3"

tasks:
  gems:
    desc: Scrape skill gem data from POEDB and save to JSON
    cmds:
      - poetry run python scripts/scrape_skill_gems.py
    silent: false

  classes:
    desc: Scrape class/ascendancy data from POEDB and save to JSON
    cmds:
      - poetry run python scripts/scrape_classes.py
    silent: false
